apiVersion: v1
kind: Pod
metadata:
  name: postgres-migration-pod
  namespace: pr1sm
spec:
  containers:
  - name: migration
    image: alpine:3.18
    command: ["/bin/sh", "-c", "sleep 3600"]
    volumeMounts:
    - name: postgres-data
      mountPath: /var/lib/postgresql/data
  volumes:
  - name: postgres-data
    persistentVolumeClaim:
      claimName: postgres-storage-postgres-0
  restartPolicy: Never 