FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
      build-essential gcc && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install flask duckdb pyjwt dotenv pandas 

COPY ./src /app

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]